import Foundation
import Summarization

/// Renders the meeting minutes in Confluence's *storage* format (XHTML).
///
/// This format was chosen over ADF: it accepts native macros (`expand`, `jira`,
/// `panel`) with simple, stable markup, whereas ADF imposes a much more
/// verbose node structure for the same result.
///
/// The section order follows that of the meeting type: a daily opens on
/// blockers, a retro on how the team is feeling.
public enum ConfluenceStorageRenderer {
    public static func render(
        summary: MeetingSummary,
        transcript: String,
        audioNote: String?,
        template: MeetingTemplate = .generic,
        language: SummaryLanguage = .french
    ) -> String {
        var parts: [String] = []

        let realAttendees = summary.attendees.filter {
            !["moi", "participants"].contains($0.lowercased())
        }
        if !realAttendees.isEmpty {
            let label = language.pick(fr: "Participants", en: "Attendees")
            parts.append(
                "<p><strong>\(label) :</strong> "
                    + "\(escaped(realAttendees.joined(separator: ", ")))</p>"
            )
        }

        for section in template.sections where summary.hasContent(section) {
            parts.append(contentsOf: render(section: section, of: summary, language: language))
        }

        // The full transcript is useful but bulky: collapsed by default.
        let body = transcript
            .components(separatedBy: "\n")
            .filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
            .map { "<p>\(escaped(stripMarkdown($0)))</p>" }
            .joined()
        parts.append(expand(
            title: language.pick(fr: "Transcript intégral", en: "Full transcript"),
            body: body
        ))

        var footer = "<p><em>"
            + language.pick(fr: "Compte rendu généré par SmartMeet", en: "Minutes generated by SmartMeet")
            + " (\(escaped(template.name)))"
        if let audioNote { footer += " — \(escaped(audioNote))" }
        footer += ".</em></p>"
        parts.append(footer)

        return parts.joined()
    }

    private static func render(
        section: SummarySection,
        of summary: MeetingSummary,
        language: SummaryLanguage
    ) -> [String] {
        let heading = section.displayName(in: language)
        switch section {
        case .tldr:
            return ["<p><strong>TL;DR —</strong> \(escaped(summary.tldr))</p>"]

        case .blockers:
            // Alert box: in a daily, this is the only information that calls for
            // immediate action, it must jump out at you.
            return [panel(
                type: summary.blockers.contains { $0.severity == .blocking } ? "warning" : "note",
                title: heading,
                body: "<ul>" + summary.blockers.map { blocker in
                    let marker = blocker.severity == .blocking ? "🛑" : "⚠️"
                    let who = blocker.person.map { "<strong>\(escaped($0))</strong> — " } ?? ""
                    return "<li>\(marker) \(who)\(escaped(blocker.description))</li>"
                }.joined() + "</ul>"
            )]

        case .participantReports:
            return ["<h2>\(escaped(heading))</h2>"] + summary.participantReports.map { report in
                var block = "<h3>\(escaped(report.person))</h3>"
                if !report.done.isEmpty {
                    block += "<p><em>Fait</em></p>" + list(report.done)
                }
                if !report.next.isEmpty {
                    block += "<p><em>À venir</em></p>" + list(report.next)
                }
                if !report.blockers.isEmpty {
                    block += "<p><em>Bloqué par</em></p>" + list(report.blockers)
                }
                return block
            }

        case .moods:
            var rows = ["<tr><th>Personne</th><th>Ressenti</th><th>Commentaire</th></tr>"]
            for mood in summary.moods {
                let icon = switch mood.mood {
                case .positive: "🙂"
                case .neutral: "😐"
                case .negative: "🙁"
                }
                rows.append(
                    "<tr>"
                        + "<td>\(escaped(mood.person))</td>"
                        + "<td>\(icon) \(escaped(mood.mood.rawValue))</td>"
                        + "<td>\(escaped(mood.comment))</td>"
                        + "</tr>"
                )
            }
            return [
                "<h2>\(escaped(heading))</h2>",
                "<table><tbody>" + rows.joined() + "</tbody></table>",
            ]

        case .sprintWeather:
            // Section shared with managers, named per person: each person gets
            // their own block, with their icons, justification, and their take
            // on the sprint.
            return ["<h2>\(escaped(heading))</h2>"] + summary.sprintWeather.map { entry in
                let icons = entry.icons
                    .map { "\($0.emoji) \(escaped($0.label(in: language)))" }
                    .joined(separator: " · ")
                var block = "<h3>\(escaped(entry.person))</h3>"
                if !icons.isEmpty { block += "<p>\(icons)</p>" }
                if !entry.explanation.isEmpty {
                    block += "<p>\(escaped(entry.explanation))</p>"
                }
                if !entry.sprintFeedback.isEmpty {
                    block += list(entry.sprintFeedback)
                }
                return block
            }

        case .fourL:
            guard let fourL = summary.fourL else { return [] }
            var parts = ["<h2>\(escaped(heading))</h2>"]
            for axis in fourL.axes(in: language) where !axis.topics.isEmpty {
                parts.append("<h3>\(escaped(axis.label))</h3>")
                for topic in axis.topics {
                    if !topic.heading.isEmpty {
                        parts.append("<p><strong>\(escaped(topic.heading))</strong></p>")
                    }
                    parts.append(list(topic.bullets))
                }
            }
            return parts

        case .topics:
            return summary.topics
                .filter { !$0.heading.isEmpty }
                .flatMap { ["<h2>\(escaped($0.heading))</h2>", list($0.bullets)] }

        case .decisions:
            return ["<h2>\(escaped(heading))</h2>", list(summary.decisions)]

        case .actionItems:
            return ["<h2>\(escaped(heading))</h2>", actionItemsTable(summary.actionItems)]

        case .openQuestions:
            return ["<h2>\(escaped(heading))</h2>", list(summary.openQuestions)]

        case .nextSteps:
            return ["<h2>\(escaped(heading))</h2>", list(summary.nextSteps)]
        }
    }

    static func list(_ items: [String]) -> String {
        let visible = items.filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
        guard !visible.isEmpty else { return "<p><em>Aucun</em></p>" }
        return "<ul>" + visible.map { "<li>\(escaped($0))</li>" }.joined() + "</ul>"
    }

    static func actionItemsTable(_ items: [MeetingSummary.ActionItem]) -> String {
        var rows = ["<tr><th>Responsable</th><th>Action</th><th>Échéance</th><th>Ticket</th></tr>"]
        for item in items {
            let ticket = item.jiraKey.map(jiraMacro) ?? "—"
            rows.append(
                "<tr>"
                    + "<td>\(escaped(item.owner ?? "—"))</td>"
                    + "<td>\(escaped(item.description))</td>"
                    + "<td>\(escaped(item.dueDate ?? "—"))</td>"
                    + "<td>\(ticket)</td>"
                    + "</tr>"
            )
        }
        return "<table><tbody>" + rows.joined() + "</tbody></table>"
    }

    static func jiraMacro(_ key: String) -> String {
        "<ac:structured-macro ac:name=\"jira\">"
            + "<ac:parameter ac:name=\"key\">\(escaped(key))</ac:parameter>"
            + "</ac:structured-macro>"
    }

    static func expand(title: String, body: String) -> String {
        "<ac:structured-macro ac:name=\"expand\">"
            + "<ac:parameter ac:name=\"title\">\(escaped(title))</ac:parameter>"
            + "<ac:rich-text-body>\(body)</ac:rich-text-body>"
            + "</ac:structured-macro>"
    }

    static func panel(type: String, title: String, body: String) -> String {
        "<ac:structured-macro ac:name=\"\(type)\">"
            + "<ac:parameter ac:name=\"title\">\(escaped(title))</ac:parameter>"
            + "<ac:rich-text-body>\(body)</ac:rich-text-body>"
            + "</ac:structured-macro>"
    }

    /// The transcript is stored in markdown; markup is stripped before escaping.
    static func stripMarkdown(_ line: String) -> String {
        line.replacingOccurrences(of: "**", with: "")
            .replacingOccurrences(of: "^#+\\s*", with: "", options: .regularExpression)
    }

    /// Strict XML escaping: the storage format rejects a malformed entity and
    /// makes the whole page fail.
    public static func escaped(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}
