import Atlassian
import Foundation
import Notion
import Observation
import Summarization

/// Settings persisted in `UserDefaults`, excluding secrets which go to the keychain.
@MainActor
@Observable
public final class AppSettings {
    private enum Key {
        static let provider = "summaryProvider"
        static let opencodeModel = "opencodeModel"
        static let copilotACPModel = "copilotACPModel"
        static let ollamaModel = "ollamaModel"
        static let locale = "transcriptionLocale"
        static let vocabulary = "vocabulary"
        static let knownPeople = "knownPeople"
        static let atlassian = "atlassianConfiguration"
        static let autoSummarize = "autoSummarize"
        static let useCalendar = "useCalendar"
        static let customTemplates = "customTemplates"
        static let defaultTemplate = "defaultTemplateID"
        static let userName = "userName"
        static let outputLanguage = "outputLanguage"
        static let detectMeetings = "detectMeetings"
        static let autoStartOnDetection = "autoStartOnDetection"
        static let detectMeetingEnd = "detectMeetingEnd"
        static let autoPublish = "autoPublish"
        static let autoCreateJiraIssues = "autoCreateJiraIssues"
        static let diarizeMicrophoneTrack = "diarizeMicrophoneTrack"
        static let notion = "notionConfiguration"
        static let disabledTemplateIDs = "disabledTemplateIDs"
        static let recentTranscriptionLocales = "recentTranscriptionLocales"
    }

    private let defaults = UserDefaults.standard
    private let keychain = KeychainStore()
    private let notionKeychain = KeychainStore(service: "com.smartmeet.notion")
    static let tokenAccount = "atlassian-api-token"
    static let notionTokenAccount = "notion-integration-token"

    public var providerKind: SummaryProviderKind {
        didSet { defaults.set(providerKind.rawValue, forKey: Key.provider) }
    }
    public var opencodeModel: String {
        didSet { defaults.set(opencodeModel, forKey: Key.opencodeModel) }
    }
    public var copilotACPModel: String {
        didSet { defaults.set(copilotACPModel, forKey: Key.copilotACPModel) }
    }
    public var ollamaModel: String {
        didSet { defaults.set(ollamaModel, forKey: Key.ollamaModel) }
    }
    public var localeIdentifier: String {
        didSet { defaults.set(localeIdentifier, forKey: Key.locale) }
    }
    /// Recently used spoken languages, most recent first — lets them surface
    /// at the top of the picker instead of getting lost in the framework's
    /// full list of supported locales.
    public var recentTranscriptionLocales: [String] {
        didSet { defaults.set(recentTranscriptionLocales, forKey: Key.recentTranscriptionLocales) }
    }
    public var vocabulary: [String] {
        didSet { defaults.set(vocabulary, forKey: Key.vocabulary) }
    }
    /// First (and last) names of people the user regularly interacts with,
    /// spelled correctly. Kept separate from the domain vocabulary to stay
    /// readable, but used exactly the same way: injected into speech
    /// recognition and into the minutes prompt, so that a name misheard or
    /// misspelled by the model corrects itself.
    public var knownPeople: [String] {
        didSet { defaults.set(knownPeople, forKey: Key.knownPeople) }
    }
    /// User's name: the transcript only knows them by the label "Moi" ("Me").
    public var userName: String {
        didSet { defaults.set(userName, forKey: Key.userName) }
    }
    /// Default language proposed for the minutes.
    public var defaultOutputLanguage: SummaryLanguage {
        didSet { defaults.set(defaultOutputLanguage.rawValue, forKey: Key.outputLanguage) }
    }
    /// Suggests recording when a meeting is detected.
    public var detectMeetings: Bool {
        didSet { defaults.set(detectMeetings, forKey: Key.detectMeetings) }
    }
    /// Starts without asking. Deliberately off by default: recording people
    /// without their knowledge isn't a behavior you turn on on their behalf.
    public var autoStartOnDetection: Bool {
        didSet { defaults.set(autoStartOnDetection, forKey: Key.autoStartOnDetection) }
    }
    /// Suggests (never forces) stopping and generating the minutes when the
    /// tracked video-conferencing app has stopped picking up the microphone
    /// for a while. On by default: it's just a notification, symmetric to
    /// `detectMeetings` — unlike `autoStartOnDetection`, nothing is stopped
    /// without the user explicitly requesting it by tapping the action.
    public var detectMeetingEnd: Bool {
        didSet { defaults.set(detectMeetingEnd, forKey: Key.detectMeetingEnd) }
    }
    public var autoSummarize: Bool {
        didSet { defaults.set(autoSummarize, forKey: Key.autoSummarize) }
    }
    /// Publishes to Confluence without review. Off by default: the minutes
    /// are generated by a model, they deserve a look before landing on a
    /// team space.
    public var autoPublish: Bool {
        didSet { defaults.set(autoPublish, forKey: Key.autoPublish) }
    }
    /// Also creates Jira tickets during an automatic publication.
    public var autoCreateJiraIssues: Bool {
        didSet { defaults.set(autoCreateJiraIssues, forKey: Key.autoCreateJiraIssues) }
    }
    public var useCalendar: Bool {
        didSet { defaults.set(useCalendar, forKey: Key.useCalendar) }
    }
    /// Experimental microphone-track diarization: distinguishes up to two
    /// speakers sharing the same microphone (in-person meeting), based on
    /// classic acoustic features — not a speech-recognition model. Off by
    /// default: the separation can get it wrong, especially if the two
    /// voices sound alike.
    public var diarizeMicrophoneTrack: Bool {
        didSet { defaults.set(diarizeMicrophoneTrack, forKey: Key.diarizeMicrophoneTrack) }
    }
    /// Meeting types created by the user, in addition to the built-in templates.
    public var customTemplates: [MeetingTemplate] {
        didSet {
            guard let data = try? JSONEncoder().encode(customTemplates) else { return }
            defaults.set(data, forKey: Key.customTemplates)
        }
    }
    /// Template proposed by default when starting a recording.
    public var defaultTemplateID: String {
        didSet { defaults.set(defaultTemplateID, forKey: Key.defaultTemplate) }
    }

    public var atlassian: AtlassianConfiguration {
        didSet {
            guard let data = try? JSONEncoder().encode(atlassian) else { return }
            defaults.set(data, forKey: Key.atlassian)
        }
    }

    /// API token: read from and written to the keychain, never to the preferences.
    public var atlassianToken: String {
        didSet { keychain.write(atlassianToken, account: Self.tokenAccount) }
    }

    public var notion: NotionConfiguration {
        didSet {
            guard let data = try? JSONEncoder().encode(notion) else { return }
            defaults.set(data, forKey: Key.notion)
        }
    }

    /// Notion integration token: keychain, never the preferences.
    public var notionToken: String {
        didSet { notionKeychain.write(notionToken, account: Self.notionTokenAccount) }
    }

    /// Meeting types (built-in or custom) deliberately hidden from the
    /// selection list. Not deleted — just absent from `allTemplates` — to
    /// stay reversible and not break anything in the history of meetings
    /// already recorded with this type.
    public var disabledTemplateIDs: Set<String> {
        didSet {
            defaults.set(Array(disabledTemplateIDs), forKey: Key.disabledTemplateIDs)
        }
    }

    public init() {
        providerKind = SummaryProviderKind(
            rawValue: defaults.string(forKey: Key.provider) ?? ""
        ) ?? .opencode
        opencodeModel = defaults.string(forKey: Key.opencodeModel) ?? "github-copilot/claude-sonnet-5"
        copilotACPModel = defaults.string(forKey: Key.copilotACPModel) ?? "claude-sonnet-5"
        ollamaModel = defaults.string(forKey: Key.ollamaModel) ?? "gemma4"
        localeIdentifier = defaults.string(forKey: Key.locale) ?? "fr-FR"
        recentTranscriptionLocales = defaults.stringArray(forKey: Key.recentTranscriptionLocales) ?? []
        vocabulary = defaults.stringArray(forKey: Key.vocabulary) ?? [
            "Confluence", "Jira", "SmartMeet",
        ]
        knownPeople = defaults.stringArray(forKey: Key.knownPeople) ?? []
        userName = defaults.string(forKey: Key.userName) ?? NSFullUserName()
        defaultOutputLanguage = SummaryLanguage(
            rawValue: defaults.string(forKey: Key.outputLanguage) ?? ""
        ) ?? .french
        detectMeetings = defaults.object(forKey: Key.detectMeetings) as? Bool ?? true
        autoStartOnDetection = defaults.object(forKey: Key.autoStartOnDetection) as? Bool ?? false
        detectMeetingEnd = defaults.object(forKey: Key.detectMeetingEnd) as? Bool ?? true
        autoSummarize = defaults.object(forKey: Key.autoSummarize) as? Bool ?? true
        autoPublish = defaults.object(forKey: Key.autoPublish) as? Bool ?? false
        autoCreateJiraIssues = defaults.object(forKey: Key.autoCreateJiraIssues) as? Bool ?? false
        useCalendar = defaults.object(forKey: Key.useCalendar) as? Bool ?? true
        diarizeMicrophoneTrack = defaults.object(forKey: Key.diarizeMicrophoneTrack) as? Bool ?? false

        if let data = defaults.data(forKey: Key.customTemplates),
           let decoded = try? JSONDecoder().decode([MeetingTemplate].self, from: data) {
            customTemplates = decoded
        } else {
            customTemplates = []
        }
        defaultTemplateID = defaults.string(forKey: Key.defaultTemplate)
            ?? MeetingTemplate.generic.id

        if let data = defaults.data(forKey: Key.atlassian),
           let decoded = try? JSONDecoder().decode(AtlassianConfiguration.self, from: data) {
            atlassian = decoded
        } else {
            atlassian = AtlassianConfiguration()
        }

        if let data = defaults.data(forKey: Key.notion),
           let decoded = try? JSONDecoder().decode(NotionConfiguration.self, from: data) {
            notion = decoded
        } else {
            notion = NotionConfiguration()
        }

        disabledTemplateIDs = Set(defaults.stringArray(forKey: Key.disabledTemplateIDs) ?? [])

        let keychain = KeychainStore()
        keychain.seedFromEnvironmentIfNeeded(
            account: Self.tokenAccount, variable: "ATLASSIAN_API_TOKEN"
        )
        atlassianToken = keychain.read(account: Self.tokenAccount) ?? ""

        let notionKeychain = KeychainStore(service: "com.smartmeet.notion")
        notionKeychain.seedFromEnvironmentIfNeeded(
            account: Self.notionTokenAccount, variable: "NOTION_API_TOKEN"
        )
        notionToken = notionKeychain.read(account: Self.notionTokenAccount) ?? ""
    }

    public var locale: Locale { Locale(identifier: localeIdentifier) }

    /// Domain vocabulary and names combined: this is what needs to be
    /// injected into speech recognition and into the prompt, not just one
    /// or the other.
    public var contextualVocabulary: [String] { vocabulary + knownPeople }

    public func makeProvider() -> any SummaryProvider {
        switch providerKind {
        case .opencode: OpencodeProvider(model: opencodeModel)
        case .copilotACP: CopilotACPProvider(model: copilotACPModel)
        case .appleOnDevice: AppleFoundationModelProvider()
        case .ollama: OllamaProvider(model: ollamaModel)
        }
    }

    public var canPublish: Bool {
        atlassian.isConfluenceReady && !atlassianToken.isEmpty
    }

    public var canPublishToNotion: Bool {
        !notionToken.isEmpty
    }

    /// Current sprint page, common parent of the sprint's meetings.
    public var sprintPage: SprintPage? {
        get { atlassian.sprintPage }
        set { atlassian.sprintPage = newValue }
    }

    /// True if at least one meeting type relies on the sprint page.
    public var usesSprintPage: Bool {
        allTemplates.contains { $0.parent.isSprintPage }
    }

    /// Built-in templates then custom templates, in display order. An edited
    /// built-in type is represented by its current version (the possible
    /// override in `customTemplates`), not the original hardcoded version.
    /// Hidden types (`disabledTemplateIDs`) don't appear here: this is the
    /// list offered for selection, not the full inventory.
    public var allTemplates: [MeetingTemplate] {
        let effectiveBuiltIns = MeetingTemplate.builtIns.map { template(id: $0.id) }
        let trueCustoms = customTemplates.filter { custom in
            !MeetingTemplate.builtIns.contains { $0.id == custom.id }
        }
        return (effectiveBuiltIns + trueCustoms).filter { !disabledTemplateIDs.contains($0.id) }
    }

    /// All types, including hidden ones — for the settings screen which
    /// must allow showing them again.
    public var allTemplatesIncludingDisabled: [MeetingTemplate] {
        let effectiveBuiltIns = MeetingTemplate.builtIns.map { template(id: $0.id) }
        let trueCustoms = customTemplates.filter { custom in
            !MeetingTemplate.builtIns.contains { $0.id == custom.id }
        }
        return effectiveBuiltIns + trueCustoms
    }

    public func isTemplateEnabled(_ template: MeetingTemplate) -> Bool {
        !disabledTemplateIDs.contains(template.id)
    }

    /// Hides or shows a type again in the selection list. If the hidden type
    /// was the default type, falls back to the generic one so as not to
    /// propose an unreachable type on the next startup.
    public func setTemplateEnabled(_ enabled: Bool, for template: MeetingTemplate) {
        if enabled {
            disabledTemplateIDs.remove(template.id)
        } else {
            disabledTemplateIDs.insert(template.id)
            if defaultTemplateID == template.id { defaultTemplateID = MeetingTemplate.generic.id }
        }
    }

    public func template(id: String?) -> MeetingTemplate {
        MeetingTemplate.resolve(id: id, in: customTemplates)
    }

    /// Bumps a spoken language to the front of the "recent" list, so it
    /// appears at the top of the picker next time. Called when the language
    /// is actually used (start of recording), not on every selection change
    /// in the picker.
    public func recordTranscriptionLocaleUsed(_ identifier: String) {
        var recents = recentTranscriptionLocales.filter { $0 != identifier }
        recents.insert(identifier, at: 0)
        recentTranscriptionLocales = Array(recents.prefix(5))
    }

    /// Duplicates a template to create an independent variant, with a new
    /// identifier.
    public func duplicate(_ template: MeetingTemplate) -> MeetingTemplate {
        var copy = template
        copy.id = UUID().uuidString
        copy.name = L("%@ (copie)", template.name)
        copy.isBuiltIn = false
        customTemplates.append(copy)
        return copy
    }

    /// Saves a template, whether it's custom or an edit of a built-in type:
    /// in both cases it's an override stored by identifier.
    public func upsert(_ template: MeetingTemplate) {
        if let index = customTemplates.firstIndex(where: { $0.id == template.id }) {
            customTemplates[index] = template
        } else {
            customTemplates.append(template)
        }
    }

    /// For a custom type, permanent deletion. For an edited built-in type,
    /// removes the override and thus reverts to the original version.
    public func remove(_ template: MeetingTemplate) {
        customTemplates.removeAll { $0.id == template.id }
        if defaultTemplateID == template.id { defaultTemplateID = MeetingTemplate.generic.id }
    }
}
