import Foundation

/// A usage context (work, personal, a specific client…) that scopes which
/// meeting types are offered, which business vocabulary is injected, which
/// service minutes are published to by default, and how the app behaves
/// around recording, detection and publication.
///
/// Per-service credentials and configuration (Notion parent page, Atlassian
/// site, API tokens…) are *also* scoped per profile, but their concrete
/// types (`AtlassianConfiguration`, `NotionConfiguration`) live in modules
/// this one can't depend on without a dependency cycle (`Atlassian` already
/// depends on `Summarization`). `AppSettings` stores them in dictionaries
/// keyed by `Profile.id` instead — see `AppSettings.atlassian`/`.notion`.
public struct Profile: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var name: String
    public var symbol: String
    /// Business vocabulary and proper nouns specific to this profile, injected
    /// into speech recognition and the minutes prompt.
    public var vocabulary: [String]
    /// People regularly involved in meetings under this profile, used for
    /// transcription hints and prompt context.
    public var knownPeople: [String]
    /// People configured for recurring one-to-ones under this profile: each
    /// carries its own publication destination and the Jira e-mail tickets
    /// should be shared with, so recording only requires picking a name.
    public var oneToOnePeople: [OneToOnePerson]
    /// Default local folder where one-to-one minutes are saved as markdown,
    /// under this profile — overridden per person by `OneToOnePerson
    /// .localFolderPath`. Empty means the feature is off: nothing is saved
    /// locally beyond the app's own on-disk store.
    public var oneToOneDefaultFolderPath: String
    /// Meeting types created by the user for this profile, in addition to the
    /// built-in templates.
    public var customTemplates: [MeetingTemplate]
    /// Allow-list of visible meeting types (built-in or custom): only these
    /// appear in the picker before recording. A fresh profile starts with
    /// only the neutral generic type — work-oriented types are opt-in per
    /// profile, not inherited automatically.
    public var enabledTemplateIDs: Set<String>
    /// Type proposed by default when starting a recording under this profile.
    public var defaultTemplateID: String
    /// Service minutes are published to by default under this profile (e.g.
    /// Confluence for "Work", Notion for "Personal"). `nil` means no
    /// particular preference — the user picks explicitly each time.
    public var defaultServiceKind: ServiceKind?
    /// Publication services added under this profile (e.g. only Notion for
    /// "Personal", only Confluence for "Work"). Their own configuration
    /// (site, token…) is kept separately in `AppSettings` even when a
    /// service is removed here, in case it's added back later.
    public var enabledServices: Set<ServiceKind>
    /// Services whose published page includes the raw transcript in a
    /// collapsed section at the bottom.
    public var servicesIncludingTranscript: Set<ServiceKind>
    /// Spoken language expected during transcription for this profile (e.g.
    /// French for "Work", English for an "International" profile).
    public var localeIdentifier: String
    /// Recently used spoken languages under this profile, most recent
    /// first, surfaced at the top of the picker.
    public var recentTranscriptionLocales: [String]
    /// Default language proposed for the minutes under this profile.
    public var defaultOutputLanguage: SummaryLanguage
    /// Languages offered in the minutes-language picker under this profile.
    /// A new profile deliberately starts with English only; additional
    /// languages are opt-in from Settings.
    public var enabledOutputLanguages: Set<SummaryLanguage>
    /// Suggests recording when a meeting is detected, under this profile.
    public var detectMeetings: Bool
    /// Starts without asking, under this profile. Off by default: recording
    /// people without their knowledge isn't a behavior turned on on their
    /// behalf.
    public var autoStartOnDetection: Bool
    /// Suggests (never forces) stopping and generating the minutes when the
    /// tracked video-conferencing app has stopped picking up the microphone
    /// for a while, under this profile.
    public var detectMeetingEnd: Bool
    /// Generates the minutes automatically after a recording, under this
    /// profile.
    public var autoSummarize: Bool
    /// Publishes to the default service without review, under this profile.
    /// Off by default: the minutes are generated by a model, they deserve a
    /// look before landing anywhere.
    public var autoPublish: Bool
    /// Also creates Jira tickets during an automatic publication, under this
    /// profile.
    public var autoCreateJiraIssues: Bool
    /// Creates Notion tasks from selected action items when automatic
    /// publication targets Notion.
    public var autoCreateNotionTasks: Bool
    /// Experimental microphone-track diarization for this profile: off by
    /// default, the separation can get it wrong, especially if the two
    /// voices sound alike.
    public var diarizeMicrophoneTrack: Bool

    /// Service used when publication is triggered without asking. An enabled
    /// explicit default wins; otherwise a single enabled service is
    /// unambiguous. Multiple services without a default deliberately resolve
    /// to `nil` so the app never publishes to an arbitrary destination.
    public var effectivePublicationServiceKind: ServiceKind? {
        if let defaultServiceKind, enabledServices.contains(defaultServiceKind) {
            return defaultServiceKind
        }
        return enabledServices.count == 1 ? enabledServices.first : nil
    }

    public func effectivePublicationServiceKind(for template: MeetingTemplate) -> ServiceKind? {
        if let serviceKind = template.serviceKind {
            return enabledServices.contains(serviceKind) ? serviceKind : nil
        }
        return effectivePublicationServiceKind
    }

    public init(
        id: String = UUID().uuidString,
        name: String,
        symbol: String = "person.crop.circle",
        vocabulary: [String] = [],
        knownPeople: [String] = [],
        oneToOnePeople: [OneToOnePerson] = [],
        oneToOneDefaultFolderPath: String = "",
        customTemplates: [MeetingTemplate] = [],
        enabledTemplateIDs: Set<String>? = nil,
        defaultTemplateID: String? = nil,
        defaultServiceKind: ServiceKind? = nil,
        enabledServices: Set<ServiceKind> = [],
        servicesIncludingTranscript: Set<ServiceKind> = [.atlassian],
        localeIdentifier: String = "fr-FR",
        recentTranscriptionLocales: [String] = [],
        defaultOutputLanguage: SummaryLanguage = .english,
        enabledOutputLanguages: Set<SummaryLanguage> = [.english],
        detectMeetings: Bool = true,
        autoStartOnDetection: Bool = false,
        detectMeetingEnd: Bool = true,
        autoSummarize: Bool = true,
        autoPublish: Bool = false,
        autoCreateJiraIssues: Bool = false,
        autoCreateNotionTasks: Bool = false,
        diarizeMicrophoneTrack: Bool = false
    ) {
        self.id = id
        self.name = name
        self.symbol = symbol
        self.vocabulary = vocabulary
        self.knownPeople = knownPeople
        self.oneToOnePeople = oneToOnePeople
        self.oneToOneDefaultFolderPath = oneToOneDefaultFolderPath
        self.customTemplates = customTemplates
        self.enabledTemplateIDs = enabledTemplateIDs ?? [MeetingTemplate.personal.id]
        self.defaultTemplateID = defaultTemplateID ?? MeetingTemplate.personal.id
        self.defaultServiceKind = defaultServiceKind
        self.enabledServices = enabledServices
        self.servicesIncludingTranscript = servicesIncludingTranscript
        self.localeIdentifier = localeIdentifier
        self.recentTranscriptionLocales = recentTranscriptionLocales
        self.defaultOutputLanguage = defaultOutputLanguage
        self.enabledOutputLanguages = enabledOutputLanguages.isEmpty
            ? [defaultOutputLanguage]
            : enabledOutputLanguages.union([defaultOutputLanguage])
        self.detectMeetings = detectMeetings
        self.autoStartOnDetection = autoStartOnDetection
        self.detectMeetingEnd = detectMeetingEnd
        self.autoSummarize = autoSummarize
        self.autoPublish = autoPublish
        self.autoCreateJiraIssues = autoCreateJiraIssues
        self.autoCreateNotionTasks = autoCreateNotionTasks
        self.diarizeMicrophoneTrack = diarizeMicrophoneTrack
    }

    private enum CodingKeys: String, CodingKey {
        case id, name, symbol, vocabulary, knownPeople, oneToOnePeople, oneToOneDefaultFolderPath
        case customTemplates
        case enabledTemplateIDs, defaultTemplateID, defaultServiceKind
        case enabledServices, servicesIncludingTranscript, localeIdentifier, recentTranscriptionLocales
        case defaultOutputLanguage, enabledOutputLanguages, detectMeetings, autoStartOnDetection
        case detectMeetingEnd, autoSummarize, autoPublish, autoCreateJiraIssues, autoCreateNotionTasks
        case diarizeMicrophoneTrack
    }
    // Tolerant decoding: a profile saved before a field existed should still
    // load, with a sensible default rather than failing the whole array.
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        symbol = try container.decodeIfPresent(String.self, forKey: .symbol) ?? "person.crop.circle"
        vocabulary = try container.decodeIfPresent([String].self, forKey: .vocabulary) ?? []
        knownPeople = try container.decodeIfPresent([String].self, forKey: .knownPeople) ?? []
        oneToOnePeople = try container.decodeIfPresent(
            [OneToOnePerson].self, forKey: .oneToOnePeople
        ) ?? []
        oneToOneDefaultFolderPath = try container.decodeIfPresent(
            String.self, forKey: .oneToOneDefaultFolderPath
        ) ?? ""
        customTemplates = try container.decodeIfPresent(
            [MeetingTemplate].self, forKey: .customTemplates
        ) ?? []
        enabledTemplateIDs = try container.decodeIfPresent(
            Set<String>.self, forKey: .enabledTemplateIDs
        ) ?? [MeetingTemplate.personal.id]
        defaultTemplateID = try container.decodeIfPresent(String.self, forKey: .defaultTemplateID)
            ?? MeetingTemplate.personal.id
        defaultServiceKind = try container.decodeIfPresent(
            ServiceKind.self, forKey: .defaultServiceKind
        )
        enabledServices = try container.decodeIfPresent(
            Set<ServiceKind>.self, forKey: .enabledServices
        ) ?? []
        if container.contains(.servicesIncludingTranscript) {
            let rawServices = (try? container.decode([String].self, forKey: .servicesIncludingTranscript)) ?? []
            servicesIncludingTranscript = Set(rawServices.compactMap(ServiceKind.init(rawValue:)))
        } else {
            // Preserve the behavior that existed before this setting:
            // Confluence included the transcript, Notion did not.
            servicesIncludingTranscript = [.atlassian]
        }
        localeIdentifier = try container.decodeIfPresent(String.self, forKey: .localeIdentifier)
            ?? "fr-FR"
        recentTranscriptionLocales = try container.decodeIfPresent(
            [String].self, forKey: .recentTranscriptionLocales
        ) ?? []
        let decodedDefaultOutputLanguage = try container.decodeIfPresent(
            SummaryLanguage.self, forKey: .defaultOutputLanguage
        ) ?? .english
        // Profiles written before this allow-list existed adopt the same
        // English-only baseline as a newly created profile. Explicitly saved
        // allow-lists remain authoritative on subsequent launches.
        let rawEnabledLanguages = (try? container.decodeIfPresent(
            [String].self, forKey: .enabledOutputLanguages
        )) ?? nil
        let decodedLanguages = Set((rawEnabledLanguages ?? [SummaryLanguage.english.rawValue])
            .compactMap(SummaryLanguage.init(rawValue:)))
        let normalizedLanguages: Set<SummaryLanguage> = decodedLanguages.isEmpty
            ? [.english]
            : decodedLanguages
        enabledOutputLanguages = normalizedLanguages
        defaultOutputLanguage = normalizedLanguages.contains(decodedDefaultOutputLanguage)
            ? decodedDefaultOutputLanguage
            : SummaryLanguage.allCases.first { normalizedLanguages.contains($0) } ?? .english
        detectMeetings = try container.decodeIfPresent(Bool.self, forKey: .detectMeetings) ?? true
        autoStartOnDetection = try container.decodeIfPresent(
            Bool.self, forKey: .autoStartOnDetection
        ) ?? false
        detectMeetingEnd = try container.decodeIfPresent(Bool.self, forKey: .detectMeetingEnd)
            ?? true
        autoSummarize = try container.decodeIfPresent(Bool.self, forKey: .autoSummarize) ?? true
        autoPublish = try container.decodeIfPresent(Bool.self, forKey: .autoPublish) ?? false
        autoCreateJiraIssues = try container.decodeIfPresent(
            Bool.self, forKey: .autoCreateJiraIssues
        ) ?? false
        autoCreateNotionTasks = try container.decodeIfPresent(
            Bool.self, forKey: .autoCreateNotionTasks
        ) ?? false
        diarizeMicrophoneTrack = try container.decodeIfPresent(
            Bool.self, forKey: .diarizeMicrophoneTrack
        ) ?? false
    }
}
