import Foundation

/// Token consumption of a call (or a cumulated series of calls) to a provider.
///
/// The two providers don't expose the same precision: `opencode` (via
/// Copilot) returns exact counts and an estimated cost, `ollama` only returns
/// tokens (no cost, since inference is local). All fields are therefore optional.
public struct TokenUsage: Sendable, Codable, Equatable {
    public var input: Int?
    public var output: Int?
    public var reasoning: Int?
    public var cacheWrite: Int?
    public var cacheRead: Int?
    /// Estimated cost in dollars, when the provider supplies it (opencode/Copilot).
    public var costUSD: Double?

    public init(
        input: Int? = nil,
        output: Int? = nil,
        reasoning: Int? = nil,
        cacheWrite: Int? = nil,
        cacheRead: Int? = nil,
        costUSD: Double? = nil
    ) {
        self.input = input
        self.output = output
        self.reasoning = reasoning
        self.cacheWrite = cacheWrite
        self.cacheRead = cacheRead
        self.costUSD = costUSD
    }

    /// Sum of everything that transited (input + output + reasoning + cache),
    /// i.e. what is generally billed.
    public var total: Int {
        (input ?? 0) + (output ?? 0) + (reasoning ?? 0) + (cacheWrite ?? 0) + (cacheRead ?? 0)
    }

    /// Accumulates two measurements — useful when a generation chains several
    /// calls (chunking, invalid JSON repairs…).
    public static func + (lhs: TokenUsage, rhs: TokenUsage) -> TokenUsage {
        TokenUsage(
            input: sum(lhs.input, rhs.input),
            output: sum(lhs.output, rhs.output),
            reasoning: sum(lhs.reasoning, rhs.reasoning),
            cacheWrite: sum(lhs.cacheWrite, rhs.cacheWrite),
            cacheRead: sum(lhs.cacheRead, rhs.cacheRead),
            costUSD: sumDouble(lhs.costUSD, rhs.costUSD)
        )
    }

    private static func sum(_ a: Int?, _ b: Int?) -> Int? {
        guard a != nil || b != nil else { return nil }
        return (a ?? 0) + (b ?? 0)
    }

    private static func sumDouble(_ a: Double?, _ b: Double?) -> Double? {
        guard a != nil || b != nil else { return nil }
        return (a ?? 0) + (b ?? 0)
    }

    /// Human-readable summary for the UI or headless logs.
    public var formatted: String {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        numberFormatter.groupingSeparator = " "
        let tokens = numberFormatter.string(from: NSNumber(value: total)) ?? "\(total)"
        guard let costUSD else {
            return String(
                format: NSLocalizedString("%@ tokens", bundle: .main, value: "%@ tokens", comment: ""),
                tokens
            )
        }
        return String(
            format: NSLocalizedString(
                "%@ tokens (≈ %@ $)", bundle: .main, value: "%@ tokens (≈ %@ $)", comment: ""
            ),
            tokens, String(format: "%.3f", costUSD)
        )
    }
}

/// Text generated by a provider, along with its consumption when known.
public struct SummaryCompletion: Sendable {
    public let text: String
    public let usage: TokenUsage?

    public init(text: String, usage: TokenUsage? = nil) {
        self.text = text
        self.usage = usage
    }
}

/// Accumulator that sums up the `TokenUsage` received over the course of a
/// generation's calls (chunking, repairs…). `SummaryGenerator.generate`'s
/// `onUsage` callbacks are `@Sendable`: this class avoids having each caller
/// synchronize a captured variable itself.
public final class UsageBox: @unchecked Sendable {
    private let lock = NSLock()
    private var accumulated: TokenUsage?

    public init() {}

    public func add(_ usage: TokenUsage) {
        lock.lock()
        defer { lock.unlock() }
        accumulated = (accumulated ?? TokenUsage()) + usage
    }

    public var total: TokenUsage? {
        lock.lock()
        defer { lock.unlock() }
        return accumulated
    }
}
